version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: iskcon_vizag_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iskcon_vizag_db
      MYSQL_USER: devotee
      MYSQL_PASSWORD: devotee_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  db-admin:
    image: adminer:latest
    container_name: iskcon_vizag_adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  mysql_data:
